# Generated by Django 2.2.1 on 2021-06-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('uploading', '上传中')], default='uploading', help_text='状态', max_length=10, verbose_name='状态'),
        ),
    ]
