# Generated by Django 2.2 on 2021-07-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='branch',
            field=models.CharField(blank=True, help_text='分支名', max_length=32, null=True, verbose_name='分支名'),
        ),
        migrations.AddField(
            model_name='image',
            name='record',
            field=models.FileField(blank=True, help_text='构建详情', null=True, upload_to='images/%Y/%m/%d/%H', verbose_name='构建详情'),
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, help_text='gitlab代码仓库地址', max_length=64, null=True, verbose_name='gitlab代码仓库地址'),
        ),
    ]
