# Generated by Django 2.2 on 2021-06-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='zone',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='区域'),
        ),
    ]
