# Generated by Django 2.2 on 2021-06-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_time',
            field=models.DateTimeField(blank=True, help_text='服务器到期时间', null=True, verbose_name='服务器到期时间'),
        ),
    ]
