# Generated by Django 2.2 on 2021-07-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_auto_20210623_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['-last_check']},
        ),
        migrations.AlterField(
            model_name='server',
            name='asset',
            field=models.CharField(blank=True, help_text='资产', max_length=256, null=True, verbose_name='资产号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='borrow',
            field=models.CharField(blank=True, help_text='是否借用', max_length=256, null=True, verbose_name='借用'),
        ),
        migrations.AlterField(
            model_name='server',
            name='project',
            field=models.CharField(blank=True, help_text='产品线', max_length=256, null=True, verbose_name='项目/产品'),
        ),
        migrations.AlterField(
            model_name='server',
            name='zone',
            field=models.CharField(blank=True, help_text='区域', max_length=256, null=True, verbose_name='区域'),
        ),
    ]
